### ISSUE TITLE
Add something to Readme file to describe use cases

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/default_views_config#1]
There was a discussion about this module in Gitter today, when a user was looking for a way to import a Drupal 7 view into Backdrop. In Drupal 7, an admin can import a view through the UI that has been exported from another site (or another environment). 

I believe that this user wanted to export a view from Drupal 7 and import it into Backdrop.

1) It would not have occurred to me that this is possible, except maybe during an upgrade/migration. 
2) I did not have any idea that this module existed

QUESTIONS:

1) Is the primary use case for this module to help with a D7 to Backdrop upgrade or migration?
2) Are there other practical uses?

**Comment by docwilmot** [comment]
Answers:
1. yes
2. no idea/doubt it.

Not sure what the aim of this issue is, TBH.

**Comment by stpaultim** [comment]
The purpose of opening this issue was first of all to simply better understand what the purpose of the this module is and whether or not it might be something that I could use or would be useful to me. 

I asked the question here in the module issue queue, because I can envision someone like myself stumbling across this module in the future and having the same questions. The description isn't very helpful to me:

> This module produces Backdrop-compatible config code from Drupal 7 hook_views_default_views() code.

I've been trying to direct people to contrib projects that they might not be aware of and it occurred to me that this module might be useful to people like myself in ways that are not obvious from the description. I'd be willing to help write up a more detailed description, but I need to better understand the module first.

**Comment by docwilmot** [comment]
I suppose you mean the README could be a bit more verbose then? I wouldnt be surprised, I tend toward brevity, often too much. Will try and expand a bit. Suggestions welcome though. Thanks.

**Comment by docwilmot** [comment]
How about this:

Some Drupal 7 modules may provide default Views upon install; these are provided by invoking `hook_views_default_views()` in Drupal 7, but this hook is absent in Backdrop. Default Views in backdrop are provided as JSON configuration files instead and there is no core mechanism for converting Drupal's default Views. 

When converting Drupal 7 modules to Backdrop, Default Views Convert to Config module can produce Backdrop-compatible configuration code from Drupal 7 hook_views_default_views() code.

Convert this (note this code contains two Views):
```
function hook_views_default_views() {

  // First block of Views default code providing the first View.

  $view = new view();
  $view->name = 'frontpage';
  $view->description = 'Emulates the default ...';
  ...
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'node';
  ...
  $views[$view->name] = $view;

  // Second block of Views default code.

  $view = new view();
  $view->name = 'anotherview';
  $view->description = 'Provides a View of ...';
  ...
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['query_comment'] = FALSE;
  ...
  $views[$view->name] = $view;

  return $views;
}
```

to this (note that there could be two sets of JSON code similar to this below, one for each View in the `hook_views_default_views()` code above. You only convert the ones you want.):

```
{
    "_config_name": "views.view.promoted",
    "name": "frontpage",
    "description": "Emulates the default ...",
    ...
    "base_table": "node",
    "core": 0,
    "display": {
        "default": {
            "display_title": "Master",
            "display_plugin": "default",
            "display_options": {
        ...
        "block": {
            "display_title": "Block",
            "display_plugin": "block",
            "display_options": {
    ...
}
```

Installation
-------
admin/structure/views/default-views-convert
Install as usual
Navigate to 'admin/structure/views/default-views-convert'
Follow instructions

**Comment by herbdool** [comment]
Looks good to me. Once we've got that in, a new release?

**Comment by stpaultim** [comment]
Yes, I guess my suggestion was to be a bit more verbose and descriptive about what the module actually does. I had an idea that I might be able to help with that, but I think your description is useful, but it is probably not something I could have written. 

Thanks, I think this is a big improvement and will be helpful to others.

**Comment by herbdool** [comment]
@docwilmot all looks good. Want to create a new release?

**Comment by docwilmot** [comment]
Done. Thanks for the support guys.

**Comment by markabur** [comment]
> When converting this module to Backdrop, the module developer will need to 
> provide each of these two Views in the acceptable Backdrop JSON format. Running
> each View in the `hook_views_default_views()` code above through this module 
> would produce a JSON output such as below. each would then be copied to an
> individual JSON file, one separate JSON file for each View.

What do I do with the json file after I've exported it? I want to include it in a custom module like I did in d7.

**Comment by docwilmot** [comment]
Your module will need a `/config` folder. Put the `json` file in there and Backdrop will automatically sync it to the active config files folder on module install. Youll also need a `hook_config_info()` implementation in your module so Backdrop can do cleanup when your module is uninstalled. Lots of examples in core and contrib. Good luck,

**Comment by markabur** [comment]
Thanks for the quick reply, Doc -- what if the module is already installed and I want to add some more views to it?

**Comment by docwilmot** [comment]
Still add the new json to your config folder in case you uninstall/install in future. But to get the view available just paste the json file directly into the files/active folder and flush caches.

**Comment by markabur** [comment]
Ok, and then if I release a new version of the module with some updated views, would users of the module need to go through the same process of manually copying and pasting json?

**Comment by docwilmot** [comment]
If your module is already out in general use and you add any new config or modify the database you'd need an upgrade path via `hook_upgrade_N()`. See https://docs.backdropcms.org/api/backdrop/core%21modules%21file%21file.install/function/file_update_1000/1

**Comment by markabur** [comment]
Ok, thanks.
