### ISSUE TITLE
Add menu and configure path to .info

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/default_views_config#2]
When I've used this module I always have to look up the path in the code. Rather than that lets add a menu link under the Structure > Views > Convert and also provide a link when people have successfully installed it. I can submit a PR.

**Comment by herbdool** [comment]
I made a PR https://github.com/backdrop-contrib/default_views_config/issues/2 @docwilmot 

It moves the menu link too - let me know if that's too much but thought it would make it easier to find.

**Comment by docwilmot** [comment]
Good idea, thanks.
